import type { Ad } from '@/components/AdCard'

export const ADS: Ad[] = [
  {
    id: '1',
    title: 'iPhone 14 Pro 256GB',
    price: 4200,
    city: 'Iași',
    category: 'Electronice',
    image: '/demo/iphone.jpg',
    images: ['/demo/iphone.jpg'],
    postedAt: 'Astăzi',
    description: 'iPhone 14 Pro în stare excelentă, culoare Deep Purple, stocare 256GB. Folosit cu husă și folie din prima zi.',
    ownerId: 'demo-seller',
  },
  {
    id: '2',
    title: 'Apartament 2 camere Centru',
    price: 98000,
    city: 'Suceava',
    category: 'Imobiliare',
    image: '/demo/apart.jpg',
    images: ['/demo/apart.jpg'],
    postedAt: 'Ieri',
    description: 'Apartament decomandat, etaj 3/4, mobilat modern, aproape de parc și mijloace de transport.',
    ownerId: 'demo-seller',
  },
  {
    id: '3',
    title: 'Dacia Duster 4x4 2019',
    price: 11200,
    city: 'Botoșani',
    category: 'Auto',
    image: '/demo/duster.jpg',
    images: ['/demo/duster.jpg'],
    postedAt: 'Acum 3 zile',
    description: 'Duster 1.5 dCi 4x4, unic proprietar, revizii la zi. Include set complet de anvelope iarnă.',
    ownerId: 'demo-seller',
  },
  {
    id: '4',
    title: 'Laptop ASUS i7 16GB RAM',
    price: 3200,
    city: 'Bacău',
    category: 'Electronice',
    image: '/demo/elec-laptop.jpg',
    images: ['/demo/elec-laptop.jpg'],
    postedAt: 'Astăzi',
    description: 'Laptop ASUS Vivobook Pro cu procesor i7, 16GB RAM și SSD 1TB. Perfect pentru lucru și gaming casual.',
    ownerId: 'demo-seller',
  },
  {
    id: '5',
    title: 'Casă 4 camere, teren 600mp',
    price: 125000,
    city: 'Iași',
    category: 'Imobiliare',
    image: '/demo/real-house.jpg',
    images: ['/demo/real-house.jpg'],
    postedAt: 'Acum 2 zile',
    description: 'Casă individuală P+1 cu 4 camere, curte amenajată și garaj. Proprietar direct, utilități complete.',
    ownerId: 'demo-seller',
  },
  {
    id: '6',
    title: 'Tunde gard viu – servicii',
    price: 150,
    city: 'Piatra Neamț',
    category: 'Joburi & servicii',
    image: '/demo/jobs-service.jpg',
    images: ['/demo/jobs-service.jpg'],
    postedAt: 'Ieri',
    description: 'Servicii profesionale de tuns gard viu și amenajare spații verzi. Programări flexibile.',
    ownerId: 'demo-seller',
  },
  {
    id: '7',
    title: 'Motocultor 7CP aproape nou',
    price: 2800,
    city: 'Vaslui',
    category: 'Agricultură',
    image: '/demo/agro-cultor.jpg',
    images: ['/demo/agro-cultor.jpg'],
    postedAt: 'Acum 5 zile',
    description: 'Motocultor 7CP folosit o singură sezonă, include freze și plug pentru cartofi. Transport în zonă.',
    ownerId: 'demo-seller',
  },
  {
    id: '8',
    title: 'Canapea extensibilă modernă',
    price: 1700,
    city: 'Suceava',
    category: 'Casă & grădină',
    image: '/demo/home-sofa.jpg',
    images: ['/demo/home-sofa.jpg'],
    postedAt: 'Astăzi',
    description: 'Canapea extensibilă cu spațiu de depozitare, material catifelat rezistent la pete. Transport contra cost.',
    ownerId: 'demo-seller',
  },
]
